### ISSUE TITLE
Listar y filtrar alquileres de garaje

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#10]
**Perteneciente a la Épica #7**
La tarea consiste en listar todos los alquileres publicados por usuarios disponibles en la aplicación, tanto para administradores como usuarios. Para ello, se exige:

_Frontend:_
* Listado de ofertas propias del usuario.
* Listado de ofertas públicas a todos los usuarios.
* Filtros y barra de búsqueda.

_Backend:_
* Método de listar propias.
* Método de listar ofertas públicas.

**Comment by 3ralon** [comment]
@silvglad he estado mirando el diseño del listado. Me parece bien y quería aportar alguna idea al diseño. Siéntete libre de añadir lo que quieras y  modificarlo. Desgloso aquí las propuestas, muy similares a las de los mockups:

- Vista de una tarjeta de garaje en el listado:
![image](https://github.com/Aparking/AparKing_Backend/assets/128732971/529ff1f9-cc28-41c7-917d-b25ecf72456e)

- Vista del listado con usuario (no administrador):
![image](https://github.com/Aparking/AparKing_Backend/assets/128732971/8d824da4-9b05-467b-b31e-b7b11b24781b)

- Vista del listado con administrador:
![image](https://github.com/Aparking/AparKing_Backend/assets/128732971/d280154c-2a2d-4787-a9e4-82d5484adbe7)

**Comment by silvglad** [comment]
Gracias por la sugerencia @3ralon , me parece perfecto. Ya que la funcionalidad como tal está terminada y dichos diseños que propones hay que propagarlos a las demás vistas y funcionalidades de los compañeros, propongo afrontarlo en una nueva issue más adelante en la que podamos tener todas las funcionalidades de la épica en cuestión aunadas. 
Cierro esta issue por el momento.
