### ISSUE TITLE
Actualizar Landing Page

### ISSUE THREAD

**Issue by MarioArocaPaez** [Aparking/AparKing_Backend#115]
Actualizar la landing page con la información actualizada de la nueva divsión de grupos y revisar el aspecto visual de la pagina

**Comment by MarioArocaPaez** [comment]
Landing page actualizada, podéis verla aquí :sunglasses::
https://aparking-144153767.hubspotpagebuilder.eu/aparking

**Comment by laurolmer** [comment]
Me gusta como se ve Mario, buen trabajo 💇‍♂️
