### ISSUE TITLE
Reformular ecuación para medir el esfuerzo

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#119]
Según nos dijeron en el feedback los profesores, deberíamos modificar la fórmula para tener en cuenta el trabajo específico de ciertos roles. Algo así como que la fórmula cambie en función del rol que tiene la persona, o que el rol es un factor multiplicador dentro de la ecuación.

La fórmula actual es:

![Image](https://github.com/Aparking/AparKing_Backend/assets/128732971/2759d28a-a114-4a7c-af25-d780bdc327d5)

Donde:
- **Tc**: tareas completadas esa semana.
- **Ta**: tareas asignadas esa semana.
- **Ns**: nota de la semana del integrante asignada por el coordinador/es.
- **Nc**: nota de la semana del coordinador elegida por los integrantes del equipo.

La principal asignada es @CarmenRuizPorcel. Además, @3ralon colaborará en la ejecución de la tarea.

**Comment by CarmenRuizPorcel** [comment]
Mi primera propuesta para la nueva fórmula de rendimiento es esta
Rendimiento (%) = ((N_completadas_x / N_total_x) * P_completadas_x) + (N_completadas_y / N_total_y) * P_completadas_y) + ...+ ((H_trabajadas / H_estimadas) * P_horas) + ((T_revisión / H_trabajadas) * P_revisión)) * 100%

+ **N_completadas_x** es el número de tareas de tipo x (ej. desarrollo, documentación, configuración) completadas por el integrante.
+ **N_total_x** es el número total de tareas tipo x (ej. desarrollo, documentación, configuración )asignadas.
+ **P_completadas** es el peso asignado al número de tareas completadas en el rendimiento total.
+ **H_trabajadas** es el número de horas trabajadas por el integrante.
+ **H_estimadas** es el número total de horas estimadas para todas las tareas.
+ **P_horas** es el peso asignado al tiempo trabajado en comparación con el tiempo estimado en el rendimiento total.
+ **T_revisión** es el tiempo dedicado a la revisión de tareas.
+ **P_revisión** es el peso asignado al tiempo dedicado a la revisión en el rendimiento total.
Los pesos P_completadas, P_horas y P_revisión son valores que puedes ajustar dependiendo de la importancia relativa que queramos le asignar a cada factor en el rendimiento general en cada semana. Yo sugiero el el peso lo dictamine los coordinadores al inicio de la semana.
Lo de has horas se puede hacer o en general o también por cada tipo de tarea, yo creo que por cada tipo de tarea es mejor.

**Comment by laurolmer** [comment]
Me parece bien, hay que recordar que para que no favorezca una mala repartición de tareas hay que hacer una buena asignación que no se superen las 10 horas por tareas, así que por mi parte doy el visto bueno
