### ISSUE TITLE
Elaborar un Pilot User Agreement

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#121]
El profesorado nos comentó que debíamos elaborar un documento en el que se desglose el acuerdo entre la organización y los usuarios piloto, así como un apartado en el que dejen registrado que se comprometen a ello. Se desglosan los siguientes pasos:

1. Elaborar el documento base y mostrar a los coordinadores para que estos den el visto bueno.
2. Contactar con los usuarios piloto y enviar el customer agreement en borrador para que den visto bueno de los puntos, si no hay ninguna sugerencia ni queja, elaborar el documento definitivo con firmas de los coordinadores como representantes de la organización.
3. Enviar el documento a los usuarios piloto para que se formalice el acuerdo.

Esta tarea está principalmente asignada a @MarioArocaPaez, sin embargo, @ivasansan1 y @CarmenRuizPorcel han elaborado documentación o contactado con usuarios piloto. Por lo que ayudarán a Mario.

Recalcar que esta tarea es muy importante y debemos tenerla lo antes posible terminada.

**Comment by MarioArocaPaez** [comment]
Yo sobre esto tengo la duda principalmente de ¿Cuando vamos a tener la aplicación desplegada aprox? Es que tampoco puedo dar mucha info a los usuarios piloto si no les digo cuando van a poder usar la aplicación. El acuerdo de cuanto tiempo tienen para probarla ya lo hicimos, lo único que queda es pelearnos con ellos para que no nos obliguen hacerlo todos (y obviamente elaborar el documento de manera mas formal)

**Comment by laurolmer** [comment]
La app para el sprint 1 ya está desplegada, para más info pregunta a @marvicmar o @JuanCarlosRL que son los que han hecho eso. Respecto al siguiente despliegue la intención es que esté para el día lunes 1 de abril, cuando es la entrega del sprint 2

**Comment by MarioArocaPaez** [comment]
Muy bien pues si queréis me pongo a hacer el documento, podemos estructurarlo en una sección para la gente del otro grupo que me puedo encargar yo, otra para los otros usuarios que lo puede llevar @ivasansan1 . Ya que no tiene sentido ponerle las mismas exigencias a ambos grupos y ya luego @CarmenRuizPorcel puede hacer de revisora. Si os parece bien

**Comment by MarioArocaPaez** [comment]
Comentar que después de verme la píldora teórica del Customer Agreement lo que estamos hablando aquí no es un CA como tal, podríamos decir que es más bien un Pilot User Agreement o algo así, deberíamos renombrar la issue pero no lo quiero hacer sin persmiso de @3ralon o @marvicmar 
Si os veis la píldora teórica un CA es más bien algo como esto [https://github.com/customer-terms](url) en el que un servicio especifica sus términos de servicio, planes de precio y servicios que se ofrecen. Es una tarea distinta pero que se debe hacer, por ahora yo me voy a centrar en el acuerdo de usuarios piloto :grin:

**Comment by 3ralon** [comment]
De acuerdo @MarioArocaPaez, gracias por revisar la píldora teórica. Fallo mío al utilizar la nomenclatura erróneamente. Me parece bien, renombra la issue de la forma correcta y cualquier duda nos comentas por aquí 🍔

**Comment by MarioArocaPaez** [comment]
Pues ya tenéis mi primera versión de los acuerdo que progrongo para los usuarios piloto. Lo podéis encontrar en el drive en la carpeta de la proxima presentación (No pongo el enlace por aquí porque es público xd). Espero feedback por parte de @3ralon @marvicmar y @CarmenRuizPorcel cuando podáis :point_right::point_left:
Resumidamente comentaros que los acuerdos son básicamente los ya escritos en el documento original pero de manera más formal, esto son todo propuestas que tendré que discutir de manera mas detallada yo personalmente con María pero ya os adelanto que no vamos a ceder a lo que nos quieren hacer de que todos probemos la aplicación ya que como comenta nuestra profesora esto es una práctica abusiva por parte del otro grupo
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/cbfd13c4-2303-4feb-a691-74d1391a83fc)
Importante el tema de que como es un acuerdo he puesto firmas en el documento, la mía como encargado del otro grupo, la de @ivasansan1 como encargado de los usuarios generales, la de @CarmenRuizPorcel como revisora y la de María como representante del otro grupo. En cuanto tenga vuestro ok empiezo las discusiones con el otro grupo :smiling_imp:

**Comment by laurolmer** [comment]
Buenas Mario, le he echado un ojo al documento y en primer lugar decirte que está bastante bien. En mi opinión considero que el apartado "Objetivos de la Colaboración" y "Compromisos de NexONG" del punto 3.1. es algo breve para lo importante que es realmente. Me explico, se menciona de pasada que los usuarios pilotos deben de probar la aplicación y de qué forma deben hacerlo. 
Estaría bien detallar algo más mencionando de qué manera esperamos que prueben la aplicación y la importancia que eso tiene. Por ejemplo, puedes exigirles que hagan pruebas relacionadas con la ciberseguridad como SQL Injections, etc. Cuéntame abajo qué opinas de todo esto. 
Un saludo fiera.

**Comment by 3ralon** [comment]
> Pues ya tenéis mi primera versión de los acuerdo que progrongo para los usuarios piloto. Lo podéis encontrar en el drive en la carpeta de la proxima presentación (No pongo el enlace por aquí porque es público xd). Espero feedback por parte de @3ralon @marvicmar y @CarmenRuizPorcel cuando podáis 👉👈 Resumidamente comentaros que los acuerdos son básicamente los ya escritos en el documento original pero de manera más formal, esto son todo propuestas que tendré que discutir de manera mas detallada yo personalmente con María pero ya os adelanto que no vamos a ceder a lo que nos quieren hacer de que todos probemos la aplicación ya que como comenta nuestra profesora esto es una práctica abusiva por parte del otro grupo ![imagen](https://private-user-images.githubusercontent.com/73229438/313402063-cbfd13c4-2303-4feb-a691-74d1391a83fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTAwOTgsIm5iZiI6MTcxMDU4OTc5OCwicGF0aCI6Ii83MzIyOTQzOC8zMTM0MDIwNjMtY2JmZDEzYzQtMjMwMy00ZmViLWE2OTEtNzRkMTM5MWE4M2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDExNDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ODQyYTA0N2M1MmVjZWRhZjIzMzRjNWJlYjU4NDU5MTM2MzU2ODc5OTEyZDRjYTg3OGE5NzQzYjBkNjNjOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1F_InyV3XYUYlpLGqrM2AaHoscvqBzQDYhmPLrcyyv4) Importante el tema de que como es un acuerdo he puesto firmas en el documento, la mía como encargado del otro grupo, la de @ivasansan1 como encargado de los usuarios generales, la de @CarmenRuizPorcel como revisora y la de María como representante del otro grupo. En cuanto tenga vuestro ok empiezo las discusiones con el otro grupo 😈

De acuerdo, lo he estado revisando y creo que está bastante completo 💯 . Una cosa a retocar para facilitar la elaboración de la presentación, las **fechas de evaluación proporcionadas** se podrían mostrar mediante imágenes con un calendario (adjunto foto de la sección del documento).

![image](https://github.com/Aparking/AparKing_Backend/assets/128732971/cfb5294e-1533-4096-aa3e-700532bed1e3)


Por el resto, bastante completo, no obstante, creo que añadiría una firma de alguno de los coordinadores. Y por último, la sección del resto de usuarios a completar por @ivasansan1.

**Comment by MarioArocaPaez** [comment]
Muy bien, pues tras el feedback de @laurolmer y @3ralon ya está el docu actualizado.
He extendido un poco más las secciones de "Objetivos de la Colaboración" y "Compromisos de NexONG" aunque honestamente pienso que las pruebas de seguridad rollo inyecciones SQL y tal a esta gente no les va a hacer mucha gracia, yo lo he incluido pero no me sorprendería si nos dicen que no quieren hacerlo o si nos exigen después a nosotros lo mismo (Cuidado con eso)
He añadido un calendario con las fechas de cuando estará disponible la aplicación, cuando podrán testear y cuando deberá estar todo el feedback. He usado especificamente esta plantilla de Canva para el calendario [https://www.canva.com/p/templates/EAFHI5sm48Y-calendario-2024-enero-a-mayo-mensual-con-semanas-minimalista-imprimible-a4/](url) por si @ivasansan1 quiere usar la misma para el suyo.
Y como Alberto ha comentado lo de la firma de un coordinador me he tomado la libertad de poner la suya (Voy a ir a la carcel por usurpación de identidad).
Si queréis que cambie algo más en el documento para ello estoy y si no quedo a la espera de que me deis el OK para comunicarme con el otro grupo :kissing_heart:

**Comment by laurolmer** [comment]
perfecto Mario muchas gracias, respecto a lo de las pruebas de seguridad y pruebas sobre los formularios que tenga la aplicación, no les queda otra, por cada fallo que ellos no encuentren y que el profesorado sí, puntos que pierden, así que la situación juega a nuestro favor en ese sentido

**Comment by CarmenRuizPorcel** [comment]
@MarioArocaPaez El documento está genial muy buen trabajo 😸 . Pero creo que habría que añadir un par de cosas para que esté perfecto del todo:
- En la parte de Compromiso del Equipo de Aparking creo que nosotros deberiamos comprometernos a proporcionarles una guía de usuario para que sepan como funciona la app y que funcionalidad probar. Así nos aseguramos que no están muy perdidos de primeras con la app y vayan directamente a lo que necesitamos que testeen. Además esa guía también se le prometió a los usuarios pilotos externos, así que habría que hacerla de todas formas.
- En la parte de responsables de comunicación indicaría como os vais a comunicar en discord, tipo una sección en nuestro canal o por mensajes privados de discord. (Esto es un poco por manía mía pero creo que está bien que lo aclaremos)
- Añade a @marvicmar como coordinadora en las firmas, los dos son coordinadores y deberían estar por si los usuarios pilotos quieren contactar a ellos que tengan ambas opciones y María le de el visto bueno también.

Por otro lado, añade esto ya a docusaurus 🦖 . La idea principal de usar docusaurus es tener un seguimiento de las versiones del documento y todos estos cambios que se han pedido previamente no se han registrado 🤓 ☝ .

**Comment by CarmenRuizPorcel** [comment]
@3ralon @marvicmar Aunque a esta issue se le haya cambiado el nombre de Costumer agreement a Pilot User agreement, no deberiamos olvidarnos de redactar el Costumer agreement porque nos va a hacer falta para nuestros usuarios finales 😅

**Comment by MarioArocaPaez** [comment]
Ya estaría todo lo que me ha comentado @CarmenRuizPorcel Aquí tenéis el enlace de docusaurus `https://base-conocimiento-g11.vercel.app/docs/Planificaci%C3%B3n%20proyecto/Acuerdo%20de%20Usuarios%20Piloto`
Puedo ponerme ya a hablar con el otro grupo? @3ralon @marvicmar

**Comment by laurolmer** [comment]
Por mí sí, dale duro

**Comment by 3ralon** [comment]
> Ya estaría todo lo que me ha comentado @CarmenRuizPorcel Aquí tenéis el enlace de docusaurus https://base-conocimiento-g11.vercel.app/docs/Planificaci%C3%B3n%20proyecto/Acuerdo%20de%20Usuarios%20Piloto Puedo ponerme ya a hablar con el otro grupo? @3ralon @marvicmar

Lo acabo de leer entero, me parece que está genial. Llega el momento de ponerse en marcha y hacer la propuesta al otro grupo, negociando lo que haga falta. ¡Ánimo compañero, lo estás haciendo genial!

**Comment by 3ralon** [comment]
> @3ralon @marvicmar Aunque a esta issue se le haya cambiado el nombre de Costumer agreement a Pilot User agreement, no deberiamos olvidarnos de redactar el Costumer agreement porque nos va a hacer falta para nuestros usuarios finales 😅

Cierto, voy a crear ya la issue para que no se nos pase. Gracias @CarmenRuizPorcel!!

**Comment by laurolmer** [comment]
Dada que esta tarea ha sido realizada por @MarioArocaPaez, revisada por varias personas y la otra parte que quedaba ha sido migrada a otra tarea, doy esta tarea por finalizada.
