### ISSUE TITLE
Actualizar análisis de costes

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#122]
Debido a unos cambios en las tecnologías del proyecto, el documento de análisis de costes actual no representa un desglose correcto de los costes de la organización. Por tanto:

- [x] Corregir tecnologías empleadas y elaborar tabla de costes unitarios.
- [x] Estimar costes desde tres perspectivas: pesimista, realista, optimista.
- [x] Actualizar gráficas de costes.

Esta tarea pertenece a @3ralon, pero en caso de necesitar ayuda, @laurolmer echará un cable.

**Comment by laurolmer** [comment]
Lo veo correcto, bien hecho Alberto
