### ISSUE TITLE
Implementar estilos en los garajes

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#125]
@silvglad he estado mirando el diseño del listado. Me parece bien y quería aportar alguna idea al diseño. Siéntete libre de añadir lo que quieras y  modificarlo. Desgloso aquí las propuestas, muy similares a las de los mockups:

- Vista de una tarjeta de garaje en el listado:
![image](https://github.com/Aparking/AparKing_Backend/assets/128732971/529ff1f9-cc28-41c7-917d-b25ecf72456e)

- Vista del listado con usuario (no administrador):
![image](https://github.com/Aparking/AparKing_Backend/assets/128732971/8d824da4-9b05-467b-b31e-b7b11b24781b)

- Vista del listado con administrador:
![image](https://github.com/Aparking/AparKing_Backend/assets/128732971/d280154c-2a2d-4787-a9e4-82d5484adbe7)

_Originally posted by @3ralon in https://github.com/Aparking/AparKing_Backend/issues/10#issuecomment-1987224313_

**Comment by 3ralon** [comment]
Debido a que esta funcionalidad se ha implementado por diferentes integrantes, el resultado en lo que a estilos se refiere no es uniforme. Por ello, abro esta issue para registrar estos cambios que tendremos que llevar a cabo. Los diferentes diseños los iremos plasmando por aquí a través de capturas de pantalla.

El principal asignado es @silvglad ya que los diseños los mencioné en su issue. Sin embargo, todos los asociados a esta funcionalidad debemos colaborar en la medida de lo posible @ivasansan1, @laurolmer y @3ralon.

**Comment by laurolmer** [comment]
Vale, ayudaré en lo que pueda

**Comment by laurolmer** [comment]
He aprovechado mi funcionalidad ya que tenía que toquetear html y he arrastrado esta tarea a la [mía ](https://github.com/Aparking/AparKing_Frontend/issues/26)
