### ISSUE TITLE
Test: Creación, edición y borrado de alquiler de zona de garaje

### ISSUE THREAD

**Issue by laurolmer** [Aparking/AparKing_Backend#129]
**Funcionalidad objeto de pruebas**
Se prueba añadir alquileres con distintos datos en los formularios, para ver las buenas prácticas de tests de formularios según su tipo revise el apartado correspondiente de Discussions. Probar los permisos de cada usuario, que un admin y usuario normal puedan crear un alquiler, que los admin puedan editar y borrar todos los alquileres y los usuarios solamente los suyos.

**Metodología de pruebas**
Tests unitarios para probar tanto casos positivos como negativos.

colaboradora @CarmenRuizPorcel

**Comment by CarmenRuizPorcel** [comment]
En cuento se mergee la rama #369 se puede cerrar la issue sin problema
