### ISSUE TITLE
Listado de incidencias

### ISSUE THREAD

**Issue by laurolmer** [Aparking/AparKing_Backend#138]
**Descripción de la funcionalidad a implementar**
Habilitar que el administrador pueda visualizar todas las incidencias de todos los usuarios y que los usuarios puedan ver sus incidencias.

**Motivo para su implementación**
Para que se puedan visualizar todas las incidencias y sea más legible por el administrador

**Comment by silvglad** [comment]
Cerrada por duplicada de #34
