### ISSUE TITLE
Generar un StoryBoard

### ISSUE THREAD

**Issue by laurolmer** [Aparking/AparKing_Backend#141]
Realizar un storyboard con el contexto de la aplicación siguiendo las enseñanzas de las píldoras teóricas

**Comment by CarmenRuizPorcel** [comment]
Está genial Laura, le alegro mucho de que puedas usar tus dotes artísticas para este proyecto 😄 🥳

**Comment by laurolmer** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73184962/4809973e-00f7-46ef-90a9-3184dd4a3c3c)
Para hacer esto ajsdjasjd
