### ISSUE TITLE
Elaborar un Customer Agreement

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#144]
@3ralon @marvicmar Aunque a esta issue se le haya cambiado el nombre de Costumer agreement a Pilot User agreement, no deberiamos olvidarnos de redactar el Costumer agreement porque nos va a hacer falta para nuestros usuarios finales 😅

_Originally posted by @CarmenRuizPorcel in https://github.com/Aparking/AparKing_Backend/issues/121#issuecomment-2002098937_

Elaborar un acuerdo con el cliente en el que se expongan los servicios ofrecidos por parte de la organización, los planes de membresía y los derechos y obligaciones del cliente.

**Comment by MarioArocaPaez** [comment]
He estado editando el documento ya que hay que revisar si tiene clausulas abusivas en Claudette. Antes las tenía pero ya no :)
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/531cbaaf-2e28-421e-9f69-456e5bedc4b5)
