### ISSUE TITLE
Elaborar presentación 19/03

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#145]
Elaborar la presentación para el día 19/03. Las tareas a realizar:
- [x] Revisar índice de la presentación y decidir orden del contenido.
- [x] Elaborar diapositivas incluyendo imágenes y toda la información relevante.
- [x] Revisar todas las diapositivas y el objetivo de comunicación y ASEGURAR QUE LA PLANIFICACIÓN TIENE LOS SPRINTS ESPECIFICADOS

Todo el personal es bienvenido para elaborar la presentación @Aparking/g1 @Aparking/g3. Como estas semanas atrás, los presentadores será @3ralon.

**Comment by MarioArocaPaez** [comment]
Contad conmigo :fire::fire::fire:
Vamos a cocinar cositas :smiling_imp::curry::sushi::poultry_leg::pizza::hamburger::meat_on_bone:

**Comment by CarmenRuizPorcel** [comment]
Contad conmigo también 🕺 🤓
