### ISSUE TITLE
Elaborar la guía de usuario para los usuarios piloto

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#149]

**Comment by MarioArocaPaez** [comment]
Esta guía ya está hecha, se encontraba al principio de la encuesta de los usuarios piloto. Ya que para la versión que se le ha dado a los usuarios piloto realmente no se necesita más. Queda pendiente para el próximo Sprint hacer una mejor (a diferencia de lo que han hecho ellos que han asumido que íbamos a saber todo de su aplicación sin ninguna guia)
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/7a282a66-9c6a-4699-879d-329d2b491e55)
