### ISSUE TITLE
Implementar mapa en tiempo real

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#15]
**Perteneciente a la Épica #14**
La tarea consiste en la implementación de un mapa como página principal de la aplicación. Para ello, se exige:

_Frontend:_
* Vista del mapa: que se muestre el mapa y los botones necesarios.
* Búsqueda de localización.

_Backend:_
* Llamada a la API del mapa. Investigar cómo funciona la API.
* Modelo de datos que gestiona la información de la localización y el destino (algoritmo de matchmaking).

**Comment by sergiosant02** [comment]
Es importante aplicar la documentación de django para instalar POSGIShttps://docs.djangoproject.com/en/5.0/ref/contrib/gis/tutorial/
