### ISSUE TITLE
watch_theory_pill_Replanning, Story Boards, and Expenses_Revenues Estimation

### ISSUE THREAD

**Issue by MarioArocaPaez** [Aparking/AparKing_Backend#152]
Ver la píldora teórica Replanning, Story Boards, and Expenses_Revenues Estimation . Importante controlar el tiempo que pasáis en esta Issue con Clockify usando la etiqueta "Teoría". Una vez hayáis visto la píldora responded a esta Issue con una captura de pantalla de que la habéis visto.
Recordad que si no lo hacéis es motivo de suspenso individual :blush:
Esta es una tarea que todo el mundo debe hacer @sergiosant02 @JuanCarlosRL @PedroRuizAguilar @CarmenRuizPorcel @alepervaz @laurolmer @virolialo @MarioArocaPaez @silvglad @JoseJavierAlcobendas @marvicmar @ivasansan1 @IsmaelRuizJurado @3ralon

**Comment by laurolmer** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73184962/0304624d-c4e6-4fb3-a94c-5ab8b49d6c34)
Another one

**Comment by CarmenRuizPorcel** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/72879200/fd40fa2f-43c7-4254-be6b-c8f21f1553fc)

Lo mio son las dos theory pills de la semana 7, me las vi juntas. Además hice apuntes para facilitar el repaso de los compaleros 😎

**Comment by IsmaelRuizJurado** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/100471083/415cea96-653d-401c-b000-3a088fbdd58b)
✍️(◔◡◔)

**Comment by silvglad** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73229659/5e2085b5-a522-429d-8a31-7a396af7a4ac)
✌️

**Comment by PedroRuizAguilar** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/72878120/ff5fe3a4-3331-4a66-ac3e-7c7c2359336a)

**Comment by JoseJavierAlcobendas** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73230697/2f2118f7-8307-4681-8ba9-1a1f894c46a9)

**Comment by sergiosant02** [comment]
![Captura de pantalla 2024-03-30 a las 12 30 15](https://github.com/Aparking/AparKing_Backend/assets/54277294/03da63b8-d315-40d3-b860-b2cc36f8ac07)

**Comment by virolialo** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73227047/b58c835a-aea3-4d5f-9e5e-365cc96bd530)

**Comment by alepervaz** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73081268/b0b62c1d-0572-4ca6-b365-3a507dd2fb7a)

**Comment by 3ralon** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/128732971/85c259f2-4afb-4aea-9d1f-f116872653ba)

**Comment by marvicmar** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73558808/de04a975-35bb-43a0-97f1-3ff724d4314c)
