### ISSUE TITLE
watch_theory_pill_Testing 

### ISSUE THREAD

**Issue by MarioArocaPaez** [Aparking/AparKing_Backend#153]
Ver la píldora teórica Testing  . Importante controlar el tiempo que pasáis en esta Issue con Clockify usando la etiqueta "Teoría". Una vez hayáis visto la píldora responded a esta Issue con una captura de pantalla de que la habéis visto.
Recordad que si no lo hacéis es motivo de suspenso individual :blush:
Esta es una tarea que todo el mundo debe hacer @sergiosant02 @JuanCarlosRL @PedroRuizAguilar @CarmenRuizPorcel @alepervaz @laurolmer @virolialo @MarioArocaPaez @silvglad @JoseJavierAlcobendas @marvicmar @ivasansan1 @IsmaelRuizJurado @3ralon

**Comment by laurolmer** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73184962/d2ce340b-238a-4175-ae5c-6e272348a544)
aquí tienes crack

**Comment by CarmenRuizPorcel** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/72879200/b35f0a41-42a5-4e1b-83ee-fc696372f62e)
Lo mio son las dos theory pills de la semana 7, me las vi juntas. Además hice apuntes para facilitar el repaso de los compaleros 😎

**Comment by IsmaelRuizJurado** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/100471083/48493df5-5d90-45bc-a72d-4c1a432628aa)
✍️(◔◡◔)

**Comment by MarioArocaPaez** [comment]
@CarmenRuizPorcel Cuidado que esa no va aquí

**Comment by MarioArocaPaez** [comment]
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/88ee0a60-ce76-4298-962c-17729b599d95)

**Comment by silvglad** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73229659/9e76eacc-e68b-4d81-b89b-1af05ce3ccc7)
📲

**Comment by sergiosant02** [comment]
<img width="948" alt="Captura de pantalla 2024-03-22 a las 7 36 44" src="https://github.com/Aparking/AparKing_Backend/assets/54277294/ef4e800a-f444-42d7-9ea6-d19a7a00fcf1">
Lo mío es la pildora teórica un poco acelerada y cogiendo algunas notas importantes.

**Comment by PedroRuizAguilar** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/72878120/fe146882-d54a-4392-8e85-3aa27d38301c)

**Comment by JoseJavierAlcobendas** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73230697/edf36b89-868c-46e3-ac88-8d4e7acc47af)

**Comment by virolialo** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73227047/643fd657-0cd8-454a-9999-f80bde37edae)

**Comment by alepervaz** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73081268/e6e3f650-da59-4f5e-ace6-a950649b5661)

**Comment by 3ralon** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/128732971/4e563eb3-e289-45e7-90f5-10b9ab35f129)
