### ISSUE TITLE
watch_theory_pill_customer_agreement

### ISSUE THREAD

**Issue by MarioArocaPaez** [Aparking/AparKing_Backend#154]
Ver la píldora teórica Customer_agreement . Importante controlar el tiempo que pasáis en esta Issue con Clockify usando la etiqueta "Teoría". Una vez hayáis visto la píldora responded a esta Issue con una captura de pantalla de que la habéis visto.
Recordad que si no lo hacéis es motivo de suspenso individual :blush:
Esta es una tarea que todo el mundo debe hacer @sergiosant02 @JuanCarlosRL @PedroRuizAguilar @CarmenRuizPorcel @alepervaz @laurolmer @virolialo @MarioArocaPaez @silvglad @JoseJavierAlcobendas @marvicmar @ivasansan1 @IsmaelRuizJurado @3ralon

**Comment by MarioArocaPaez** [comment]
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/e85f5ddd-ca31-4b25-83f3-3ddabd6d77d1)

**Comment by laurolmer** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73184962/fac7bd34-6dd2-472d-8ce5-ca81dfcc83c9)
Yo me la vi el sábado. Btw, ¿hace falta que en el clockify tengamos un nombre específico pa la tarea?

**Comment by MarioArocaPaez** [comment]
> ![image](https://private-user-images.githubusercontent.com/73184962/314624678-5d8f7092-f8cb-43bc-868f-7c12f17e68dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NjAxODIsIm5iZiI6MTcxMDk1OTg4MiwicGF0aCI6Ii83MzE4NDk2Mi8zMTQ2MjQ2NzgtNWQ4ZjcwOTItZjhjYi00M2JjLTg2OGYtN2MxMmYxN2U2OGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDE4MzgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMWM4OTM1ZDljNzMzYzZmODVjYzhiOGMyMjNmNzdkZTIzMzZmMDMzZTJmZDExM2RlYmU1NjJiYTAyMTUyYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qX9NS53Y3-fctAJfebW3lt5V6pexBmJMhq7x-fArcwY) Yo me la vi el sábado. Btw, creo que tenemos que tener este nombre

La mejor práctica es que tenga el mismo nombre de la issue y lo hayas hecho con la extensión de clocky con la issue. Pero si ya lo hiciste te perdono

**Comment by IsmaelRuizJurado** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/100471083/bedfafa8-10ec-43fe-b29e-2d8d5b2f7550)
✍️(◔◡◔)

**Comment by ivasansan1** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/95249149/75623f1d-5475-4c3f-9d21-211e35714911)

**Comment by PedroRuizAguilar** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/72878120/c4890186-1ab4-4269-97f3-58a019163bfc)

**Comment by JoseJavierAlcobendas** [comment]
![screenshot20240330110420](https://github.com/Aparking/AparKing_Backend/assets/73230697/67b79160-fdc8-4c40-a45c-7c090a55093c)

**Comment by sergiosant02** [comment]
![Captura de pantalla 2024-03-30 a las 12 45 49](https://github.com/Aparking/AparKing_Backend/assets/54277294/ad17fc67-b111-4d0f-b891-2e06a9b151bc)

**Comment by virolialo** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73227047/77d912cc-02d0-4e25-939c-a9467e88de4b)

**Comment by CarmenRuizPorcel** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/72879200/8e047135-08af-410f-8342-caf1ea072076)

**Comment by alepervaz** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73081268/89919940-79ef-4d08-8939-36e4d68af443)

**Comment by 3ralon** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/128732971/aa08ddb6-88af-4231-a92f-c78a104be0e6)

**Comment by marvicmar** [comment]
![Image](https://github.com/Aparking/AparKing_Backend/assets/73558808/b6b9d390-edd9-4e76-af1a-7a5091f07598)

**Comment by JuanCarlosRL** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/72872031/1b493130-680a-4887-9f88-b3246dbe0b98)
