### ISSUE TITLE
Fix error in develop test

### ISSUE THREAD

**Issue by alepervaz** [Aparking/AparKing_Backend#157]
**Describir el bug**
error en los test al hacer mergeo con la rama develop

**Capturas de pantalla**
![image](https://github.com/Aparking/AparKing_Backend/assets/73081268/09c892f9-10a6-4660-9669-60b113674e06)

**Contenido adicional (Opcional)**
El error se debe a una modificación de uno de los atributos de las entidades

**Comment by marvicmar** [comment]
Este error se ha solventado ya en otra rama de la misma rama, se solucionara con el mergeo, te cierro la issue.
