### ISSUE TITLE
Hacer de Usuarios Piloto para el grupo 5

### ISSUE THREAD

**Issue by MarioArocaPaez** [Aparking/AparKing_Backend#162]
Hacer de Usuarios Piloto del grupo 5 NexONG, aquí está su Landing Page:
https://ispp-g5.github.io/index.html
La encuesta que tenemos que rellenar después de hacer los tests está en la sección de usuarios piloto, tenemos que usar el de la US
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/aef6d92e-13d0-4506-823c-123fa26e66b6)
La URL de la página es la siguiente (que también está en la Landing Page)
https://nexong.ew.r.appspot.com/
Necesitamos 7 personas para realizar esto, ahora mismo somos solo 4 así que decidme si alguno queréis hacerlo.
He creado la tag "Usuario Piloto" para que os la pongáis en el clocky mientras probéis la pagina. Recordad que esto hay que hacerlo de la mejor manera posible, cada cosa que nosotros no encontremos es nota que los profesores nos quitan. Mucho animo mis compas :blush:

**Comment by laurolmer** [comment]
Yo por mi parte ya lo he analizado a fondo y he plasmado los errores aquí: https://docs.google.com/document/d/1c_a8pajL3m_u_XeJbROIrNLGkuNM4C9DuN5yTivbRLg/edit
Por favor, seguid usando este doc para anotar los fallos.

**Comment by MarioArocaPaez** [comment]
Buenas a todos, nos lo han puesto un poco difícil para las credenciales. Están en el formulario de feedback. Estas son las siguientes

Página de Inicio
- Podéis navegar a través de las diferentes pantallas. Tened en cuenta que nada de registro está implementado.
- Sabemos que las páginas "La Salle" y "Organización" están vacías.
- En "Transparencia", la descarga de archivos no funciona aún.
- Podéis hacer donaciones puntuales y sugerencias.
Panel de administrador
- Inicia sesión con el usuario [admin@gmail.com](mailto:admin@gmail.com) y contraseña admin.
- Voluntarios; puedes verlos, borrarlos y ver/aceptar/rechazar las solicitudes de los voluntarios. Por favor, no borres a la voluntaria llamada María Lorente.
- Educadores; puedes verlos y borrarlos. En un futuro el administrador también los creará, ya que los educadores no se registran en la página. Por favor, no borres al socio llamado Esteban Rodriguez.
- Socios; puedes verlos, borrarlos y convocar una asamblea.
- Eventos; puedes verlos, crearlos, borrarlos y editarlos.
- Sugerencias; puedes verlas.
Voluntarios
- Inicia sesión con el usuario [marlor@gmail.com](mailto:marlor@gmail.com) y la contraseña volutalio5.
- Puede ver y apuntarse a eventos.
Socios
- Inicia sesión con el usuario [esteban@gmail.com](mailto:esteban@gmail.com) y la contraseña parnerio1.

**Comment by laurolmer** [comment]
Hecho con las credenciales, por mi parte no mucho más, solamente deciros que reviséis mi feedback también por si acaso.
Como consejo utilizad 2 navegadores distintos por contrastar, que a mí me ha dado Opera problemas.

**Comment by PedroRuizAguilar** [comment]
Revisado el feedback de Laura y añadido algunos errores que daban las pantallas de los dos roles específicos que nos han pasado, así como otra pasada por el panel de admin, comprobando ataques de routing ( digo yo que se llama así)

**Comment by MarioArocaPaez** [comment]
> Revisado el feedback de Laura y añadido algunos errores que daban las pantallas de los dos roles específicos que nos han pasado, así como otra pasada por el panel de admin, comprobando ataques de routing ( digo yo que se llama así)

Has enviado el formulario del grupo?

**Comment by PedroRuizAguilar** [comment]
> > Revisado el feedback de Laura y añadido algunos errores que daban las pantallas de los dos roles específicos que nos han pasado, así como otra pasada por el panel de admin, comprobando ataques de routing ( digo yo que se llama así)
> 
> Has enviado el formulario del grupo?

Ya he enviado el formulario mi estimadisimo

**Comment by MarioArocaPaez** [comment]
> > > Revisado el feedback de Laura y añadido algunos errores que daban las pantallas de los dos roles específicos que nos han pasado, así como otra pasada por el panel de admin, comprobando ataques de routing ( digo yo que se llama así)
> > 
> > 
> > Has enviado el formulario del grupo?
> 
> Ya he enviado el formulario mi estimadisimo

Se lo agradezco a su merced

**Comment by virolialo** [comment]
Hola !! Acabo de revisar todo lo que habéis añadido como usuarios piloto, que he respaldado con un par de cosas nuevas que he encontrado sobre todo en validaciones.

Estoy rellenando el formulario para que tengan nota del feedback

**Comment by ivasansan1** [comment]
Tarea hecha y formulario realizado mi gente

**Comment by MarioArocaPaez** [comment]
> Tarea hecha y formulario realizado mi gente

Iván tenias que haberlo hecho ayer. El plazo limite era el miércoles y los del otro grupo se han cabreado

**Comment by MarioArocaPaez** [comment]
Tarea cerrada después de su realización
