### ISSUE TITLE
Implementar GPS para localizaciones

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#17]
Dada una ruta de origen en la que se encuentra el usuario y un destino final, se debe mostrar en el mapa el camino que debe seguir el usuario para llegar al destino.

**Comment by CarmenRuizPorcel** [comment]
Muevo esta tarea al product backlog de nuevo, debido a que hay que darle prioridad a los test de las features del sprint 1

**Comment by CarmenRuizPorcel** [comment]
Debido que para poder implementar el Mapa en aparking se necesitaba el GPS se traspasa la tarea a @sergiosant02 que es el encargado del mapa.

**Comment by sergiosant02** [comment]
Esta tarea se realizó junto a otra, por la necesidad de integrar el GPS para la misma, no se creó rama extra debido a que reultó ser la instalación de una librería unicamente

**Comment by laurolmer** [comment]
Debido al comentario previo, cierro esta tarea para evitar confusiones
