### ISSUE TITLE
Elaborar la presentación de evaluación 02/04

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#170]
Elaborar la presentación para la evaluación del 02/04. Sin embargo, tenemos que enviar las diapositivas en el entregable del 01/04. Por tanto, se desgajan en esta checklist todas las tareas que hay que hacer para la presentación:
- [x] Repasar[ feedback 19/04](https://base-conocimiento-g11.vercel.app/docs/Feedback/Semana%207) y elaborar lista de contenido para la presentación.
- [x] Repasar checklist para el entregable del 01/04.
- [x] Elaborar diapositivas.

Como colaboradores en la elaboración está el resto del equipo @Aparking/g1 @Aparking/g3.

**Comment by 3ralon** [comment]
Índice de la presentación. A medida que completemos las secciones aquí listadas debemos ir marcándolas para tener un control.

### Introducción
- [ ] Modelo de negocio
  - [ ] Killer opener
  - [ ] Elevator pitch
  - [ ] Análisis de competidores (centrarse en lo que nos diferencia)
- [ ] Nuevo story board (cambio de rol/objetivo)
- [ ] Customer agreement (términos de servicios, lo que acarrea en el desarrollo esas cláusulas. Seguir píldora teórica)
- [ ] Pricing de la aplicación
- [ ] TCO a 2 años
- [ ] Situación actual vs. Esperada y beneficios/costes pesimistas, optimistas, esperados (gráficas píldora teórica)

### Equipo
- [ ] Integrantes del equipo y sus roles
- [ ] Commitment agreement (cambios y cumplimientos)

### Demo
- [ ] Demo Sprint 2 ya desplegada con datos reales
- [ ] Incrementos en la demo, que es lo que ha mejorado con respecto a la última demo enseñada / Sprint 1 (en nuestro caso todo)

### Retrospectiva Sprint 2
- [ ] Rendimiento del equipo
  - [ ] Fórmula
  - [ ] Matriz de rendimiento y esfuerzo (y esfuerzo horas invertidas, x rendimiento obtenido en esas horas)
- [ ] Mejora del agendamiento (poner las agendas de todos y automáticamente agendar las reuniones, tipo de calendario de outlook). No es obligatorio pero muy recomendable.
- [ ] Si hay reducción de alcance del trabajo y justificar esa reducción.
- [ ] Análisis de calidad del código, enseñar cómo evoluciona a lo largo del desarrollo
- [ ] Riesgos y problemas encontrados en el sprint y cómo se han encontrado estos problemas
- [ ] Changelog para saber qué funcionalidad se va implementando nueva (automatizado mejor)
- [ ] Reloj de avance del proyecto

### Gestión de usuarios pilotos
- [ ] Estado actual
- [ ] Feedback
- [ ] Acciones tomadas a partir del feedback. Prioridades que se toman
- [ ] Preparar plan de gestión del Sprint 3 (pilot user agreeement)

### Planificación del Sprint 3
- [ ] Screenshot de las issues del S3
- [ ] Reestimación (si aplica) del S3
- [ ] Objetivos del S3
- [ ] APIs externas nuevas añadidas al proyecto. Y las implicaciones en el cálculo del OpEx

### Análisis IAs
- [ ] Estadísticas
- [ ] Analizar cómo ha mejorado el uso de las IAs a lo largo de la asignatura
- [ ] Huella de carbono que implica nuestro uso de la IA
- [ ] Lecciones aprendidas con el uso de las IAs

### Final
- [ ] Landing page
- [ ] Información de contacto
- [ ] Enlace feedback

_Esta checklist está desarrollada por nuestro compañero @MarioArocaPaez en el [docusaurus](https://base-conocimiento-g11.vercel.app/docs/Feedback/Semana%207). Simplemente la he formateado para que podamos seguir un guión para la presentación._

**Comment by virolialo** [comment]
Si queréis aparte de colaborar con el resto de tareas para la presentación, puedo hacer el de la IA por completo, para EGC en sostenibilidad se hizo un documento sobre la huella de carbono que producen las consultas por IA.

**Comment by MarioArocaPaez** [comment]
Con el tema de los usuarios piloto he añadido estas 4 diapositivas. Todas tienen sus comentarios para que entendáis cual es el propósito y tal
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/27f69ccf-95a1-4744-b6ba-9ab8c3dfc4a1)
Con el tema de las "Acciones tomadas a partir del feedback. Prioridades que se toman" no se muy bien que poner pq no lo hemos decidido

**Comment by virolialo** [comment]
> Si queréis aparte de colaborar con el resto de tareas para la presentación, puedo hacer el de la IA por completo, para EGC en sostenibilidad se hizo un documento sobre la huella de carbono que producen las consultas por IA, entonces tengo bastante info del tema.

Respecto a esto, he añadido 3 diapositivas actualizadas para completar con todo el punto, además de comentarlas para mejor comprensión por nuestros presentadores :) 
![image](https://github.com/Aparking/AparKing_Backend/assets/73227047/fa7ca576-5ed9-4a0b-bb4b-c2b57b399d27)

**Comment by MarioArocaPaez** [comment]
He añadido esta diapositiva es importante mencionar que claudette no es capaz de encontrar clausulas abusivas en nuestro customer agreement porque somos los mejores y lo hacemos todo genial
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/bf11d1ea-8f09-41c9-a01d-6bbcd6891965)
