### ISSUE TITLE
doc: Nuevo StoryBoard

### ISSUE THREAD

**Issue by laurolmer** [Aparking/AparKing_Backend#172]
Dado el feedback del pasado día 19/03, se mencionó que el storyboard era demasiado artificial, planteándolo como un problema-solución. Abro esta tarea para darle otro enfoque y mejorarlo.

**Comment by laurolmer** [comment]
@CarmenRuizPorcel me ha comentado que el storyboard nuevamente no cumplía con las expectativas del profesorado, así que vuelvo a ponerla en "in progress" y Carmen me releva en la tarea

**Comment by CarmenRuizPorcel** [comment]
Storyboard mandado por discord para tener el visto bueno del equipo

**Comment by laurolmer** [comment]
Ya se ha dado feedback al Storyboard y se puede dar por cerrada esta tarea.
