### ISSUE TITLE
Visualizar zonas de garaje en mapa

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#18]
Esta tarea busca coger los garajes que haya activos en el listado de garajes y tomando su dirección, hacer que se muestre en el mapa un icono indicando que hay un garaje en esa zona.

**Comment by marvicmar** [comment]
Se reasigna la tarea @sergiosant02 ya que tiene más relación con las tareas que ha estado realizando, y la hará en menor tiempo por tener más contexto al respecto.
