### ISSUE TITLE
Nueva versión del Failure Conditions y de las Guías de Revisión

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#187]
Se han actualizado estos documentos en la enseñanza virtual. Tareas:
- [x] Revisar documentos de la EV y ver qué secciones han cambiado.
- [x] Revisar nuestro documento de Failure Conditions Check y moverlo a la carpeta del Sprint 2.
- [x] Desarrollar el nuevo documento de Failure Conditions Check para este sprint a partir del anterior y añadiendo las nuevas cláusulas. Adjuntarlo en la carpeta del Sprint 3 del docusaurus.

**Comment by JoseJavierAlcobendas** [comment]
Estos son los nuevos requisitos que hay que añadir al docusaurus y hacerlos:

T-11) Not including in the docs repository folder the pilot users performance evaluation, evaluating
reviewer ISPP group as pilot user (PilotUsersPerformanceEvaluation.md) following the pilot users
performance evaluation template provided in EV. Each and every group must be pilot user. (e.g. Group 1
must include a PilotUsersPerformanceEvaluation.md evaluating the performance of Group 7 as pilot users).

T-12) Not including in the docs repository folder all information received from pilot users (reviewer ISPP
group) (InformationProvidedByPilotUsers.md) considering the MinimumInformationFromPilotUsers_Gathered-ByForm document. (e.g. Group 1 must include a MinimumInformationFromPilotUsers-
_GatheredByForm.md with the information obtained from Group 7 as pilot users)

T-14) Not including the following issues in your working planning representing a review performed by any
member of the group. All of them must be tracked with Clockify and the name must be as follows:
• Deployed Software review

**Comment by marvicmar** [comment]
@JoseJavierAlcobendas Estos requisitos han quedado reflejados en su correspondiente documento de nuestra base de conocimiento??

**Comment by marvicmar** [comment]
Falta actualizar los siguientes link: 

-Compromiso con las Píldoras Teóricas
-Consistencia del Contenido de la Presentación(link a la nueva presentación)
-Gestión del Feedback: Feedback
-Planificación del Trabajo para Revisiones: (TODO BACKLOG)
-Adherencia a las Guías del Revisor de Software
-Evaluación de Desempeño de Usuarios Piloto
-Documentación de Feedback de Usuarios Piloto
