### ISSUE TITLE
Actualizar evaluación del commitment agreement y matrices de rendimiento

### ISSUE THREAD

**Issue by marvicmar** [Aparking/AparKing_Backend#188]
- [x] Crear excel para calcular automáticamente el rendimiento.
- [x] Rellenar las matrices con los porcentajes de cumplimento del commitment agrement de cada miembro.
- [x] Elaborar las matrices y las gráficas para la presentación. Pensar formas creativas de mostrar esta información. Hablar con Alberto.

**Comment by CarmenRuizPorcel** [comment]
Gráficas subidas a la presentación de esta semana
