### ISSUE TITLE
Storyboard como anuncio/marketing

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#190]
Colaboradores: @CarmenRuizPorcel @MarioArocaPaez

**Comment by marvicmar** [comment]
@MarioArocaPaez como tienes esta tarea y la de la demo, y sabemos que el tema de la edición lleva tiempo si necesitas ayuda o lo que sea nos comentas.

**Comment by MarioArocaPaez** [comment]
Video acabado, lo podéis encontrar en la sección de multimedia del discord
