### ISSUE TITLE
Hacer la presentación del 09/04.

### ISSUE THREAD

**Issue by marvicmar** [Aparking/AparKing_Backend#192]
Realizar la presentación en canva, seguir para ello en índice de Müller. 

Dicho índice lo podéis encontrar también en la siguiente issue -> #183 

Colaboradores @Aparking/g1 @Aparking/g3

**Comment by MarioArocaPaez** [comment]
# Partes de la presentación

- [ ] Killer opener
- [ ] Elevator pitch
- [ ] Análisis competidores
- [ ] Storyboards como anuncio -> Convertirlo (herramientas gratuitas para ello) al menos un anuncio
- [ ] Customer agreement destacando cláusulas de términos de servicios, si hemos editado alguna cláusula y si se ha quedado alguna justificarlo. Pricing, SLA, etc.
- [ ] TCO (resumen) a dos años distinguiendo entre desarrollo y el lanzamiento, pesimista, optimista, realista, etc. Gráficas cruzadas, etc.
- [ ] Hablar del equipo, estructura
- [ ] Commitment agreement, hablar del histórico. Innovar en presentar cómo el equipo ha seguido el commitment.
- [ ] Changelog antes de la demo, demo de 1/2 sprint 3. Destacar el incremento de la demo respecto de la demo anterior. UX (píldora), datos realistas en el sistema. Cumplimientos de regulaciones, hay que empezar a garantizar privacidad -> https (GDPR te obliga).
- [ ] Retrospectiva 1/2 sprint 3. ALM, análisis calidad de código, rendimiento equipo, matriz rendimiento esfuerzo. Horas y productividad. Mejora del agendamiento. Automatización calidad del software. Plan de pruebas. Riesgos, soluciones a aplicar, cómo medimos si las soluciones llegan a los objetivos, lecciones aprendidas. Reloj de avance del proyecto
- [ ] Plan de gestión de usuarios piloto. Feedback recibido, la gestión, ranking del feedback, cómo lo vamos a implementar, etc. Commitment agreement con los usuarios piloto
- [ ] Planificación. Issues del sprint, estas issues deben tener funcionalidades como
- [ ] Planificación preliminar de la siguiente fase. Centrado en el marketing del proyecto. Refactorizaciones y tal. Empezar a pensar cómo planificar.
- [ ] Report IA, con análisis de uso
- [ ] QR, info contacto y tal.

**Comment by MarioArocaPaez** [comment]
He perdido como media hora intentando poner el logo de AparKing en el QR como tienen otros grupos que queda muy guay. Pero lo más que he conseguido es esto, si alguno sabéis como hacerlo porfa decídmelo
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/e29d9d9b-cef6-420d-9a51-d3534afe0dc1)

**Comment by sergiosant02** [comment]
He revisado la documentación existente, parace que el customer agreement está igual que la semana anterior

**Comment by sergiosant02** [comment]
He echado un ojo al Commitment, a mi parecer nosotros mostramos bien el histórico, si estás de acuerdo @MarioArocaPaez  lo damos por hecho

**Comment by sergiosant02** [comment]
He añadido una diapositiva con lo que parece (relativo a los incrementos del sprint 2), ya que del S3 aun no tenemos nada y en la anterior presentación por temas del HDMI y eso no dio tiempo a mostrarlo correctamente (en formato texto)

**Comment by sergiosant02** [comment]
He aadido méticas del codacy y revisado el orden y eso de las de equipo y tal, @MarioArocaPaez  échale un ojo si puedes

**Comment by MarioArocaPaez** [comment]
En cuanto a lo mencionado por @sergiosant02 
- Con el tema del Customer Agreement, simplemente mencionaría que es la versión 1.0 y que por ahora no hemos visto necesidad de cambiarlo
- El Commitment creo que está bastante guay como lo mostramos, lo único que ahora mismo en la diapositiva están Semana de la 1 a la 3, tenemos que actualizarlo a estas ultimas. No sé muy bien como se hace esa animación
- Con lo del progreso he cambiado las diapositivas para que se vean en tablas y sea vea algo mejor (creo yo) si no os gusta he dejado las originales ocultas y se pueden quedar. También no sé por que está lo del Sprint 3 antes del 2, entiendo que tiene más sentido poner antes el 2 no?
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/e1838a55-4dde-4d8e-80ca-3a80dff32a59)
- Con el tema del codacy y las métricas lo veo guay, pero es cierto que como llevo un par de semanas sin entrar a ayudar en la presentación hay cosas que no sé si son nuevas o de otras presentaciones o que hay que decir como tal en la diapositiva. Si no te viene mal estaría bien reunirnos en algún momento esas cosas para aclararlo.

Luego está también el tema de la demo, que es una tarea que tengo yo asignada. No sé como enfocarla ya que la cosa sería mostrar los avances del S3 pero por ejemplo en mi caso lo mio que es las reviews no puedo avanzar porque ahora mismo no puedo crear bien garajes :skull:

**Comment by sergiosant02** [comment]
@MarioArocaPaez  lo del codacy lo he añadido yo esta mañana, lo del s3 con respecto el orden, lo he puesto esta mñn, se me habrá liado el orden, puedes cambiarlo si quieres

**Comment by sergiosant02** [comment]
Y lo de cambiar lo del S3 a una tabla lo veo bien, yo lo había puesto así porque había un par de cosas parecidas en otras diapositivas pero así queda más ordenado

**Comment by sergiosant02** [comment]
El vídeo demo creo que se puede dejar el que estaba pues no ha habido avances en develop aún

**Comment by MarioArocaPaez** [comment]
> El vídeo demo creo que se puede dejar el que estaba pues no ha habido avances en develop aún

Vale, lo que si puedo hacer es editarlo para meterle zoom y que los profesores no se quejen

**Comment by MarioArocaPaez** [comment]
Presentación terminada, tenéis el enlace en nuestro discord
