### ISSUE TITLE
Riesgos: seguimiento semanal y mejora

### ISSUE THREAD

**Issue by marvicmar** [Aparking/AparKing_Backend#201]
Tareas:
- [x] Realizar el seguimiento semanal de riesgos 02/04.
- [x] Investigar una forma de medir si el plan de contingencia es efectivo.
- [x] Revisar riesgos y mejorarlos.
- [x] Realizar el seguimiento semanal de riesgos 09/04.

**Comment by laurolmer** [comment]
Ya se ha realizado la primera revisión
