### ISSUE TITLE
watch_theory_pill_on_GDPR_and_UX

### ISSUE THREAD

**Issue by MarioArocaPaez** [Aparking/AparKing_Backend#209]
Ver la píldora teórica on GDPR and UX. Importante controlar el tiempo que pasáis en esta Issue con Clockify usando la etiqueta "Teoría". Una vez hayáis visto la píldora responded a esta Issue con una captura de pantalla de que la habéis visto.
Recordad que si no lo hacéis es motivo de suspenso individual 😊
Esta es una tarea que todo el mundo debe hacer @sergiosant02 @JuanCarlosRL @PedroRuizAguilar @CarmenRuizPorcel @alepervaz @laurolmer @virolialo @MarioArocaPaez @silvglad @JoseJavierAlcobendas @marvicmar @ivasansan1 @IsmaelRuizJurado @3ralon

**Comment by IsmaelRuizJurado** [comment]
✍️(◔◡◔)
![image](https://github.com/Aparking/AparKing_Backend/assets/100471083/2af43ed7-757d-4901-b70c-1491a38c5315)

**Comment by sergiosant02** [comment]
![Image](https://github.com/Aparking/AparKing_Backend/assets/54277294/89cd1760-411b-45ee-b544-f42570452f41)

**Comment by JoseJavierAlcobendas** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73230697/54efee28-f042-4ff2-b99d-078e9b23badb)

**Comment by laurolmer** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73184962/8222450b-cb35-4bd6-b101-cd0fa43fd8b5)

**Comment by silvglad** [comment]
![Image](https://github.com/Aparking/AparKing_Backend/assets/73229659/f1d6503d-fbb7-4a1b-b1f9-bf4ec1ddfe31)

**Comment by alepervaz** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73081268/00cac616-0622-48ef-a6da-22bcab79e815)

**Comment by virolialo** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73227047/d6389d76-6978-4e99-8576-9c7e263691b3)

**Comment by marvicmar** [comment]
![Image](https://github.com/Aparking/AparKing_Backend/assets/73558808/b1adb308-42dc-4a3d-92fb-4d543704c0dd)

**Comment by MarioArocaPaez** [comment]
Me lo he puesto a velocidad 1,5 os prometo que lo he visto xd
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/b1496993-2d89-47c9-9eaa-a84ea7fa9084)

**Comment by CarmenRuizPorcel** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/72879200/a2cbf0ee-2a1e-44c4-b4c9-3648463c4984)

**Comment by PedroRuizAguilar** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/72878120/f1f67e1c-c7b1-4062-a29f-823921f88e11)

**Comment by 3ralon** [comment]
![Image](https://github.com/Aparking/AparKing_Backend/assets/128732971/d206fbbf-90fc-434a-b2e5-4aa68957cf21)

**Comment by ivasansan1** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/95249149/8d2b33fd-e900-4c7f-8249-a89172918f73)

**Comment by laurolmer** [comment]
La cierro porque todos se han visto la píldora
