### ISSUE TITLE
Elaboración de la demo del sprint 3

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#217]
- [ ] una descripción inicial de lo que se va ver destacando el incremento
  - [ ] intentar que tenga una historia realista y dinámico en el tono de voz
  - [ ] insertar el usuario que está utilizando la aplicación
  - [ ] si hay mejores de UX notificarlo en el vídeo
  - [ ] cumplimiento del GDPR, derecho al olvido, https

**Comment by MarioArocaPaez** [comment]
Muy buenas la idea de la demo será la de expandir lo mostrado en el anuncio. Tendremos a Laura y a Alberto:
![Laura](https://github.com/Aparking/AparKing_Backend/assets/73229438/f3fc6174-7b94-433f-b9a7-2e8bc9e62f12) ![Alberto](https://github.com/Aparking/AparKing_Backend/assets/73229438/fe5c0082-9342-48f5-a351-c75450b8fb35)
En una primera instancia Laura se creará una cuenta en la aplicación (Aquí se aprovechará para comentar el tema de las leyes GDPR) y subirá su aparcamiento privado para ser alquilado.
A continuación Alberto buscará aparcamientos privados, encontrará el de Laura y lo alquilará.
Después de eso veremos al final como Laura busca un aparcamiento publico usando la aplicación. En principio esa es la idea :)
