### ISSUE TITLE
Hotfix: Populate.json

### ISSUE THREAD

**Issue by marvicmar** [Aparking/AparKing_Backend#220]
**Describir el bug**
Hemos arreglado un par de errores que contenía dicho archivo. Dichos errores eran debido a un cambio de los valores del enum los cuales no se habían llevado a cabo en el archivo y la falta de una 's' en el campo is_assigment. 

**Para reproducir**
_Pasos para reproducir el comportamiento_
1. Lanzar el siguiente comando de docker para acceder a la consola (docker exec -it backend sh)
2. Realizar la carga de datos (python manage.py loaddata Populate.json)
3. Ver error

**Comportamiento esperado**
Debería realizar la carga sin errores y obtener el siguiente mensaje:

![image](https://github.com/Aparking/AparKing_Backend/assets/73558808/2a78922e-4ef2-4432-99d5-8534c571f195)

**Capturas de pantalla**
![image](https://github.com/Aparking/AparKing_Backend/assets/73558808/f8ef9af8-641c-4226-a9df-e28656d7f8f8)
![image](https://github.com/Aparking/AparKing_Backend/assets/73558808/971c2eef-7a3b-4032-a498-3a51099cf0ed)

**Comment by virolialo** [comment]
Buenos días María

¿está este cambio ya implementado en algún sitio? Necesito saberlo porque como no funciona el registro, necesito al menos un usuario con el que iniciar sesión para poder ir probando cosas del frontend. Acabo de comprobar si estuviese en la rama develop ya que la de mi tarea extiende de ahí pero según GitHub lleva sin actualizarse desde hace un mes el populate.
