### ISSUE TITLE
Hacer de Usuarios Piloto para el grupo 5

### ISSUE THREAD

**Issue by MarioArocaPaez** [Aparking/AparKing_Backend#224]
Hacer de Usuarios Piloto del grupo 5 NexONG, aquí está su Landing Page:
https://ispp-g5.github.io/index.html
La encuesta que tenemos que rellenar después de hacer los tests está en la sección de usuarios piloto, tenemos que usar el de la US
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/aef6d92e-13d0-4506-823c-123fa26e66b6)
La URL de la página es la siguiente (que también está en la Landing Page)
https://nexong.ew.r.appspot.com/
He creado la tag "Usuario Piloto" para que os la pongáis en el clocky mientras probéis la pagina. Recordad que esto hay que hacerlo de la mejor manera posible, cada cosa que nosotros no encontremos es nota que los profesores nos quitan. 
Os he vuelto a asignar a los mismos de la ultima vez. Tenemos desde el lunes 15 hasta el miércoles 17 inclusive para hacerlo
Mucho animo mis compas :blush:

**Comment by MarioArocaPaez** [comment]
Nuevo fichaje, sale @JuanCarlosRL entra @JoseJavierAlcobendas :sunglasses:

**Comment by laurolmer** [comment]
Yo ya cumplí con mi parte y envié el formulario.

**Comment by IsmaelRuizJurado** [comment]
Formulario enviado✍️(◔◡◔)✍️(◔◡◔)✍️(◔◡◔)✍️(◔◡◔)

**Comment by PedroRuizAguilar** [comment]
Formulario enviado.

**Comment by MarioArocaPaez** [comment]
Done

**Comment by virolialo** [comment]
Listo :>

**Comment by laurolmer** [comment]
Cierro la tarea porque ya se ha acabado el plazo
