### ISSUE TITLE
Fix arreglar HTTPS en despliegue

### ISSUE THREAD

**Issue by marvicmar** [Aparking/AparKing_Backend#257]
Colaborador: @sergiosant02

**Comment by marvicmar** [comment]
El problema de HTTPS en la parte del backend ya se ha solucionado, https://aparking-g11-s3.oa.r.appspot.com/.

Faltaría probar la conexión con el frontend para comprobar el correcto funcionamiento de la aplicación.  De esto se encargara @sergiosant02.

**Comment by laurolmer** [comment]
Doy por cerrada esta tarea también ya que con el despliegue del PPL se soluciona este problema
