### ISSUE TITLE
Fix acceso admin a logout

### ISSUE THREAD

**Issue by marvicmar** [Aparking/AparKing_Backend#259]
El usuario admin tras realizar el login, no le aparece el botón para deslogearse.

**Comment by sergiosant02** [comment]
Rama = Develop
Tras realizar varias pruebas, se puede ver perfectamente el botón de cerrar sesión, aun siendo admin.
![Captura de pantalla 2024-05-02 a las 16 08 51](https://github.com/Aparking/AparKing_Backend/assets/54277294/3f11d741-21a7-456a-a868-a9efd6c7c3e3)

@marvicmar , @3ralon , podríais echarle un ojo a ver si os sigue sin salir?

**Comment by 3ralon** [comment]
Se cierra esta tarea porque actualmente no da conflicto.
