### ISSUE TITLE
Fix "error datos introducidos" en login

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#260]

**Comment by sergiosant02** [comment]
Después de varias pruebas, no he sido capaz de reproducir el error, aunque todo parece indicar que es un problema de la bd, dado que la reproducción más cercana al error la he logrado cuando me he traído la rama develop y una no había aplicado los cambios a mi base de datos, es decir, no había hecho el makemigrations y y el migrate. Por favor, @marvicmar , @JuanCarlosRL o @3ralon podríais comprobar si así fuese?

**Comment by marvicmar** [comment]
Actualmente como comentas había un error con el makemigrations, y parece que ya el erro esta solventado.

**Comment by marvicmar** [comment]
Cierro la Issue ya que el error de momento no ha vuelto a saltar.
