### ISSUE TITLE
Elaborar demo mejorada

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#278]
Colaboradores: @CarmenRuizPorcel

**Comment by MarioArocaPaez** [comment]
Pausada por un pequeño problema con el programa de edición de video

**Comment by marvicmar** [comment]
Tras el feedback de esta semana se han solicitado cambios por parte de los profesores en la demo, por lo que la vuelvo a pasar a In Progress.

Cambios: 
- Centrarse en los aparcamientos por cesiones, en lugar de los libres. (Lo consideran más interesante)
- Mostrar el tema de las bonificaciones y los créditos.
- Eliminar partes que no son especificas de nuestra aplicación como el login, y recortar en general las partes donde se rellenan formularios.

La demo debe tener un hilo argumental y centrase en funcionalidades principales que suponen un factor diferenciador.

**Comment by MarioArocaPaez** [comment]
Soy el youtuber oficial de AparKing

**Comment by MarioArocaPaez** [comment]
La dejo en espera hasta que se acabe todo el desarrollo necesario
