### ISSUE TITLE
watch_theory_pill_on_market_segmentation,_traction,_and_community_management

### ISSUE THREAD

**Issue by MarioArocaPaez** [Aparking/AparKing_Backend#284]
Ver la píldora teórica on market segmentation, traction, and community management. Importante controlar el tiempo que pasáis en esta Issue con Clockify usando la etiqueta "Teoría". Una vez hayáis visto la píldora responded a esta Issue con una captura de pantalla de que la habéis visto.
Recordad que si no lo hacéis es motivo de suspenso individual 😊
Esta es una tarea que todo el mundo debe hacer @sergiosant02 @JuanCarlosRL @PedroRuizAguilar @CarmenRuizPorcel @alepervaz @laurolmer @virolialo @MarioArocaPaez @silvglad @JoseJavierAlcobendas @marvicmar @ivasansan1 @IsmaelRuizJurado @3ralon

**Comment by laurolmer** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73184962/0ed8b19c-d2ec-4632-a87b-badd1ea8afb1)
donete

**Comment by MarioArocaPaez** [comment]
Chapón histórico
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/d4d21fc1-a367-4521-93fd-4dd2dc849fa7)

**Comment by JoseJavierAlcobendas** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73230697/09723b51-62e5-492f-96d0-ce4d7a7a929f)

**Comment by IsmaelRuizJurado** [comment]
✍️(◔◡◔)
![image](https://github.com/Aparking/AparKing_Backend/assets/100471083/6c63b089-8e50-4d09-92fa-90a05a7a066d)

**Comment by alepervaz** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73081268/3b7f59d1-e8d4-40af-a14a-c54da3a761d6)

**Comment by PedroRuizAguilar** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/72878120/6d7fd6a2-1561-40a1-89a6-450fa3517593)

**Comment by marvicmar** [comment]
![Image](https://github.com/Aparking/AparKing_Backend/assets/73558808/dc264431-4d82-4ddd-99d7-f68057592313)

**Comment by JuanCarlosRL** [comment]
<img width="1271" alt="image" src="https://github.com/Aparking/AparKing_Backend/assets/72872031/091e597f-011c-46e6-ad21-1a82ee8dbd8a">

**Comment by ivasansan1** [comment]
siempre se me olvida poner esto aka xd

![Image](https://github.com/Aparking/AparKing_Backend/assets/95249149/7451a2aa-9b2f-4ab9-a5ab-6b35a51b3c14)

**Comment by virolialo** [comment]
:p 
![image](https://github.com/Aparking/AparKing_Backend/assets/73227047/68aa865f-7c2b-47af-b14d-185d0ede52a9)

**Comment by sergiosant02** [comment]
![Captura de pantalla 2024-05-06 a las 9 58 39](https://github.com/Aparking/AparKing_Backend/assets/54277294/e12f3faa-01d0-4587-aaa4-f967159ea73d)

**Comment by silvglad** [comment]
![image](https://github.com/Aparking/AparKing_Backend/assets/73229659/99dd6eab-65f3-4c8b-8bf3-b3b17ee1ebe8)
