### ISSUE TITLE
Implementar sección de leyes (SLA)

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#29]
**Perteneciente a la Épica #27**
La tarea consiste en agregar una interfaz que incluya toda la información necesaria para el usuario, teniendo en cuenta sobre todo los siguientes (Es decir, que cuando se registre debe aceptar nuestras políticas de privacidad (SLA):
* Leyes de protección de datos.
* Leyes sobre la conducción.

**Comment by MarioArocaPaez** [comment]
https://github.com/Aparking/AparKing_Frontend/pull/37
