### ISSUE TITLE
Refactor cesión de plazas de aparcamiento

### ISSUE THREAD

**Issue by marvicmar** [Aparking/AparKing_Backend#293]
Añadir o bien un campo Time o Datetime al modelo, para que el usuario a la hora de registrar su plaza de tipo **cesión**, puede seleccionar la hora a la que dejara su plaza de aparcamiento libre. 

Para que el usuario que decida reservar la plaza, sepa a que hora debe estar para que se realice el cambio de la plaza de aparcamiento entre ambos usuarios.

**Comment by marvicmar** [comment]
@laurolmer Porfa si movemos una issue de lugar, poned un comentario del motivo para poder llevar un seguimiento.

**Comment by laurolmer** [comment]
entendido, perdón
