### ISSUE TITLE
Creación de apk para distribución en android

### ISSUE THREAD

**Issue by sergiosant02** [Aparking/AparKing_Backend#295]
Tras disponer de HTTPS tanto en backend como en frontend, tenemos la posibilidad de distribuir la app mediante apk, por ello vamos a proceder a construir la misma

**Comment by sergiosant02** [comment]
@PedroRuizAguilar me puedes pasar el id de la app en admob -> admob_app_id ?

**Comment by sergiosant02** [comment]
Ya se ha construido el apk, actualmente tiene el icono y el splash en diversas plataformas pero hay un bug en este paquete por el que no muestra el splash en android 12+

**Comment by sergiosant02** [comment]
Este es el enlace para descargar el apk: https://uses0-my.sharepoint.com/:u:/g/personal/albperleo_alum_us_es/Ecfw1OA3Rp9Plqlo_YNFApoBXaeNcN540QMQgvGrtqppIg?e=ENy7BF

**Comment by laurolmer** [comment]
Como ya está comprobado cierro esta tarea
