### ISSUE TITLE
Fix Video orientado a clientes (anuncio)

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#302]
Reeditar los vídeos siguiendo el [feedback proporcionado](https://discord.com/channels/1202518928396394546/1203054927354535946/1235628332285034526).

Colaborador: @3ralon

**Comment by marvicmar** [comment]
Feedback: Recortar para que no duré más de 25 segundos / Quitar la foto de Milán.

**Comment by MarioArocaPaez** [comment]
Lo de durar menos de 25 segundos lo veo casi imposible, he recortado todo lo que he podido y estoy en 35
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/aca5ff02-896b-496e-b97b-4c8a38331bf9)

**Comment by MarioArocaPaez** [comment]
Tenéis el anuncio en discord, me quedo a la espera de cualquier feedback

**Comment by MarioArocaPaez** [comment]
El video ya está en la presentación, cierro la tarea
