### ISSUE TITLE
Fix video para inversores

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#303]
Reeditar los vídeos siguiendo el [feedback proporcionado](https://discord.com/channels/1202518928396394546/1203054927354535946/1235628332285034526).

Feedback: El pricing plan no está en sintonía con el resto del anuncio / hablar más de números / quitar lo de C2C no lo van a entender o explicarlo con palabras

Colaborador: @3ralon

**Comment by MarioArocaPaez** [comment]
Tenéis el video en #multimedia en Discord. Lo dejo en In review y quedo a la espera de que me deis algo de feedback de aspectos a mejorar

**Comment by MarioArocaPaez** [comment]
Cierro al no tener ninguna solicitud de cambio (Ya sé que lo he hecho genial :satisfied:)
