### ISSUE TITLE
Fix plan de negocio

### ISSUE THREAD

**Issue by marvicmar** [Aparking/AparKing_Backend#305]
Modificar el plan de negocio según el feedback aportado.

Feedback:  Convencer con datos numéricos proporción de personas que tienen plaza propia, cuantos no la utilizan, usar rangos, si invierten tanto dinero y se llevan x porcentaje cuando recuperan, en cuanto tiempo empiezan a ganar. 

Colaborador: @marvicmar

**Comment by laurolmer** [comment]
La cierro porque ya está la diapositiva y el docusaurus hecho
