### ISSUE TITLE
Reporte de la IA

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#310]

**Comment by MarioArocaPaez** [comment]
He añadido a la presentación las 2 IAs que he usado para tema de las voces y la canción, tenedlo en cuenta a la hora de presentar

**Comment by virolialo** [comment]
Diapositivas hechas y explicadas en la presentación :)
![image](https://github.com/Aparking/AparKing_Backend/assets/73227047/d1c7e19e-1893-4087-b91a-eb904ea31cc9)
![image](https://github.com/Aparking/AparKing_Backend/assets/73227047/2417fd7f-ff5e-480e-bb9a-ad5959e42db6)
![image](https://github.com/Aparking/AparKing_Backend/assets/73227047/9ce8e376-312e-4027-b7e8-86bfdaa06212)
