### ISSUE TITLE
Plantilla ISPP promoción

### ISSUE THREAD

**Issue by marvicmar** [Aparking/AparKing_Backend#311]
Crear diapositiva promocional según la plantilla de la enseñanza virtual, y enviarla al profesor correspondiente.

**Comment by virolialo** [comment]
Hecho, a la espera de recibir feedback de varios miembros del grupo para enviarlo :) 
![image](https://github.com/Aparking/AparKing_Backend/assets/73227047/b7e722e1-6239-4846-b0ba-a8c5e4547e10)
