### ISSUE TITLE
Fix de las cesiones y listado de vehiculos con eleccion de vehiculo 

### ISSUE THREAD

**Issue by alepervaz** [Aparking/AparKing_Backend#312]
- El objetivo de esta issue es arreglar un bug de las cesiones para cuando un usuario tenga mas de 1 coche registrado
- asimismo se creara un listado de los vehículos del usuario donde este podrá asignar su vehículo principal, lo que permitirá de forma automática asignar un coche en otras funcionales como la cesión de vehículos

**Comment by laurolmer** [comment]
Se cerró con las PR: https://github.com/Aparking/AparKing_Backend/commit/62ad8ddf15823a402980cb04cb6410048434b010 y https://github.com/Aparking/AparKing_Backend/commit/91be56bc0fcb25c8b9f4108395bf6a47796a66b2
