### ISSUE TITLE
Crear una incidencia

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#32]
**Pendiente de concretar la información tras la planificación del Sprint 3**

**Comment by MarioArocaPaez** [comment]
Implementación en el Backend de las incidencias publicadas por los usuarios, con su respectivo titulo, descripción, fecha y status 
![imagen](https://github.com/Aparking/AparKing_Backend/assets/73229438/8426dd27-c3dd-4c0d-ada8-7d27e78a6cc1)

**Comment by MarioArocaPaez** [comment]
Feat terminada en el backend. @virolialo Cuando quieras puedes hacer los tests :stuck_out_tongue_winking_eye:

**Comment by virolialo** [comment]
Genial!! Esta misma tarde me pongo y reviso además el código :)

**Comment by 3ralon** [comment]
Dejamos esta funcionalidad en stand by para asegurar la funcionalidad principal del sistema.
