### ISSUE TITLE
Mejorar la demo de Aparking

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#330]
Hay que cambiar la demo según el feedback recibido por los profesores tras la sesión PPL. Estos son los cambios a realizar:

- Cristina dijo que estaría genial que si hacemos una historia al principio (Alberto no encontraba aparcamiento en su urbanización), en la demo esto continuase esta historia. Por ello, habría que crear una historia que se hile por medio del killer opener, el anuncio y la demo.
- La demo debe hilarse con la necesidad de usar la app, centrándose en enseñar casos de usos core y menos en cosas más básicas como un registro un login o un pago. Deberíamos hablar de las cesiones entre dos coches y las plazas privadas.
- Evitar contar una historia a pasos en la demo para enseñar las funcionalidades. Hacerla según la necesidad de una persona que necesite la aplicación (esto es evitar decir primero se loguea, despues publica la plaza, despues x, etc.).

Una vez comentado esto, propongo este checklist para completarla:

- [x] Crear una historia para la presentación, que hile todo el contenido audiovisual comentado con anterioridad.
- [x] Crear una nueva demo en función del anuncio y el killer opener.

**Comment by MarioArocaPaez** [comment]
Voz: Primera persona Laura

Laura se va de viaje y alquila su garaje privado esos días

Está en la playa y encuentra un aparcamiento por cesión que alguien ha dejado

Se va a ir a x hora y deja su aparcamiento para ceder a esa hora y así ganar creditos

**Comment by MarioArocaPaez** [comment]
Videos necesarios:
-Laura crea su propio garaje y se ve
-Laura encuentra un aparcamiento que alguien cede
-Laura crea una cesión de aparcamiento a partir de una hora

Los videos deben ser grabados usando la siguiente extensión con mobiles de buen tamaño como los IPhone Pro Max: https://www.webmobilefirst.com/es/

**Comment by MarioArocaPaez** [comment]
Completada, ya tenéis la demo adjunta en la presentación
