### ISSUE TITLE
Modificar contenido del vídeo de inversores

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#332]
Hay que realizar modificaciones en el contenido de inversores tras el feedback recibido en el PPL. Esto es lo que se ha pedido:

- Los profesores recomiendan que en vez de dedicarle diapositivas a los datos de los inversores, estos números se muestren directamente en el anuncio que está dedicado a ellos. Estos datos serían de beneficio, es decir, qué obtiene un inversor si hace inversiones a Aparking. Según Cristina, a los inversores les llama más la atención los números que saber si la aplicación es escalable.
- Los números de los datos se deben redondear, no mostrar números con muchos decimales.
- Se debe evitar usar muchos iconos y sonidos para el anuncio de los inversores.

Por ello, se propone el siguiente checklist:

- [x] Pensar un plan para elaborar un nuevo anuncio de inversores, incluyendo los datos de los que se hablaron antes.
- [x] Elaborar un nuevo anuncio de inversores.

Colaboradora: @marvicmar

**Comment by MarioArocaPaez** [comment]
Ya está acabado, lo tenéis en multimedia en el servidor de discord. Como siempre si caduca el enlace de wetrasnfer me avisáis y lo vuelvo a mandar
