### ISSUE TITLE
Refactor estilos y contenido

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#337]
Según el feedback proporcionado por Elena, debemos mejorar los siguientes aspectos de la aplicación:

- [ ] El logotipo está difuminado al inicio.
- [ ] Debería incluirse las funcionalidades de cada plan de precios.
- [ ] El diseño de registro/login/perfil no es coherente con el resto de la página.
- [ ] Hay áreas de la app donde la estética varía significativamente, incluso el tipo de letra cambia.

Encargados: @virolialo @silvglad

**Comment by marvicmar** [comment]
Como estáis con los refactor de la aplicación, he estado revisando la validación de los formularios y me he dado cuenta que el formulario de añadir garaje no sigue la misma estética que el de register/login, por si podéis ajustarlo. @virolialo @silvglad

**Comment by virolialo** [comment]
> Como estáis con los refactor de la aplicación, he estado revisando la validación de los formularios y me he dado cuenta que el formulario de añadir/editar **garaje** y el de añadir/editar **vehículos** no sigue la misma estética que el de register/login, por si podéis ajustarlo. [@virolialo](https://github.com/virolialo) [@silvglad](https://github.com/silvglad)

Hola María,

Estoy encargado de modificar los estilos del login y el register, que según Elena son los que varían bastante con la página de Aparking. Cuando haga las modificaciones que sean necesarias, compruebo esto que me has dicho para ver si sería necesario hacer más cambios.
