### ISSUE TITLE
Fix validación de los formularios

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#339]
Hay formularios dentro de la aplicación que no tienen validaciones. Esta tarea es muy importante ya que es una **Failure Condition** que no se validen todos los formularios.

- [ ] Formulario de registro de vehículo.
- [ ] Formulario de creación de un alquiler de garaje.
- [ ] Se realiza la reserva de un garaje, aunque haya errores al confirmar.
- [ ] Revisar validaciones de todos los formularios.

Colaboradores: @silvglad (ponerse en contacto con @marvicmar)

**Comment by 3ralon** [comment]
Trabajando en el fix #338 he descubierto que sí que se hacen validaciones en el filtro de creación de garajes. Sin embargo, no se muestran visualmente. La imagen muestra el error de validación por consola tras haber pulsado el botón de "publicar garaje" sin rellenar todos los campos del formulario.

![Image](https://github.com/Aparking/AparKing_Backend/assets/128732971/d679696f-23de-4220-b379-5d09c06d21db)

@marvicmar @silvglad @IsmaelRuizJurado

**Comment by marvicmar** [comment]
Errores encontrados en el formulario de añadir garajes: 
- Número de plazas, número de calle y código postal se pueden poner letras 
- Porque tenemos países si solo operamos en España de momento ?? @3ralon 
-  No deja pública pero no salta en el formulario los errores

**Comment by marvicmar** [comment]
@3ralon Sí, justo probándolo me he dado cuenta que no mostraba los fallos.
