### ISSUE TITLE
Listar incidencias por el administrador

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#34]
Descripción de la funcionalidad a implementar
Habilitar que el administrador pueda visualizar todas las incidencias de todos los usuarios y que los usuarios puedan ver sus incidencias.

Motivo para su implementación
Para que se puedan visualizar todas las incidencias y sea más legible por el administrador

**Comment by marvicmar** [comment]
@silvglad Te desasigno la issue debido a que la épica se ha puesto en standby, ya que se va a modificar como se había planteado inicialmente, para simplificarla, por cuestión de tiempo.

**Comment by 3ralon** [comment]
Dejamos esta funcionalidad en stand by para asegurar la funcionalidad principal del sistema.
