### ISSUE TITLE
Implementar chat entre usuario y administrador

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#35]
Una vez declarado un usuario una incidencia, se debe generar un proceso de solventar la incidencia.

Hay dos opciones que pueden darse:
1. Implementar un chat en tiempo real entre el usuario afectado y el administrador.
2. Hacer que la forma de solucionarlo enviando un correo al administrador y que resuelvan la incidencia de manera externa a la aplicación.

**Comment by marvicmar** [comment]
@ivasansan1 Te desasigno la issue debido a que la épica se ha puesto en standby,  ya que se va a modificar como se había planteado inicialmente, para simplificarla, por  una cuestión de tiempo.

**Comment by 3ralon** [comment]
Dejamos esta funcionalidad en stand by para asegurar la funcionalidad principal del sistema.
