### ISSUE TITLE
Despliegue Frontend WPL

### ISSUE THREAD

**Issue by marvicmar** [Aparking/AparKing_Backend#370]

**Comment by sergiosant02** [comment]
Ha sido necesario crear un nuevo equipo en vercel para el despliegue, para mantener el despliegue antiguo, por ello, hemos necesitado la suscripción de prueba, disponemos de 14 días de despliegue desde hoy. Antes de esa fecha deberé de cancelar el despliegue, ya que posteriormente vercel nos cobrará dinero
