### ISSUE TITLE
Gestión de la integración continua

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#44]
Se trata de una épica del proyecto, compuesta por una única tarea, que consistirá en gestionar la integración continua del proyecto. Esto es:
* Automatizar la integración de código.
* Despliegue continuo.

Entre otros que puedan surgir.

**Comment by alepervaz** [comment]
Cierro la issue porque ya se ha elaborado la acciones para la gestión de la integración continua del proyecto
