### ISSUE TITLE
Inicialización del Backend

### ISSUE THREAD

**Issue by marvicmar** [Aparking/AparKing_Backend#45]
Esta tarea inicial busca preparar el repositorio en donde se va a alojar el backend de la aplicación. Para ello se debe preparar todas las dependencias iniciales con las herramientas que se van a usar y preparar una wiki para documentar el manual de usuario y que los demás compañeros sepan como hacer la preparación inicial.

**Comment by laurolmer** [comment]
Por mi parte veo que esta tarea está correctamente implementada y considero que puede ser cerrada ya. ¡Buen trabajo Ale!

**Comment by laurolmer** [comment]
Dado que el backend ya está completamente integrado y realizado, con su documentación y ahora con las clases del modelo, esta tarea se puede dar por finalizada.
