### ISSUE TITLE
Documentar usuarios pilotos

### ISSUE THREAD

**Issue by laurolmer** [Aparking/AparKing_Backend#52]
Perteneciente a la Épica https://github.com/Aparking/AparKing_Backend/issues/41
La tarea consiste en documentar los siguientes aspectos relacionados con los usuarios pilotos:

- Listado de usuarios pilotos, con algunos datos relevantes (qué conduce, frecuencia de uso de vehículo, zona en la que suele conducir, edad y sexo) que estén dispuestos a utilizar la aplicación.
- Declarar la frecuencia de uso y prueba de la aplicación por parte de los usuarios pilotos.
- Feedback de los usuarios pilotos para cada entregable.

**Comment by 3ralon** [comment]
Reasignada la tarea a @MarioArocaPaez

**Comment by laurolmer** [comment]
Lo veo perfecto, he cambiado cosas menores de fallos ortográficos y que en lugar de esperar que respondan las encuestas las 52 personas, que es demasiado optimista, he puesto que esperamos que como mínimo 25 (la mitad aprox) respondan
