### ISSUE TITLE
Mejorar documento de gestión de la configuración

### ISSUE THREAD

**Issue by silvglad** [Aparking/AparKing_Backend#54]
Perteneciente a la Épica #41 
La tarea consiste en  registrar todos los procedimientos de la organización para llevar a cabo un desarrollo del proyecto organizado y unificado.

- Tecnologías y Convenciones Estilísticas 
- Patrones de Épicas, Issues y Gestión de Tareas
- Estrategias de Ramificado 
- Procedimientos de Revisión de Código
- Patrones de Commit y Pull-Request
- Políticas de Integración Continua y Despliegue Continuo
- Herramientas de Gestión de la Configuración
- Plan de Respuesta ante Incidentes
- Documentación y Conocimiento

**Comment by 3ralon** [comment]
Genial @silvglad, he estado revisando el documento y aparentemente parece que todo está en orden. Cerramos esta tarea por el momento, si vemos que alguna incidencia o problema requiere modificar los patrones, reabriremos.

Buen trabajo! 😺🎈
