### ISSUE TITLE
Arreglo de Inicio y Registro de usuario

### ISSUE THREAD

**Issue by JuanCarlosRL** [Aparking/AparKing_Backend#58]
Esta issue tiene la intención de arreglar lo implementado en la issue #2

**Comment by IsmaelRuizJurado** [comment]
Ahora mismo no funciona, me sale este error: "ModuleNotFoundError: No module named 'phonenumber_field'".

También me gustaría comentar una cosa. Me parece fantástico que hagas esta corrección, pero que no se haya consultado al grupo 2 para ver si nos parece bien no tanto. Para la próxima, si se da el caso, trata de avisarlo con antelación para evitar que el trabajo de los compañeros sea en vano. Gracias.

**Comment by marvicmar** [comment]
@IsmaelRuizJurado Se os comentó que se iba a cambiar la entidad ya que no os habías ajustado al UML por una mala interpretación, al modificar dicha entidad se ha tenido que corregir como es obvio la funcionalidad. Además de que la creación del modelo al completo de la aplicación y con ello la modificación para ajustar al UML se nos ha sido asignada, yo misma estoy creando todas las entidades que van a ser necesarias a lo largo del desarrollo, y esto en principio lo sabíamos todos los coordinadores, quizás a faltado comunicación para que os llegué esta información. Por otro lado el error que comentas es por no haber realizado el pip install de los requirements de la aplicación ya que se han añadido nuevos.

**Comment by virolialo** [comment]
Buenas, me gustaría proponer cambios al modelo de de User:
* Añadir un atributo a la entidad que sea para imagen del usuario, de cara a la edición del perfil.

**Comment by marvicmar** [comment]
@virolialo Me parece buena idea y no es difícil de implementar, así que procedo añadir un nuevo atributo al User.

**Comment by virolialo** [comment]
Genial !! Además me parece tambien buena idea que se tenga una imagen default cuando se cree el usuario, como una icono de perfil si no quisiera cambiar la imagen.
