### ISSUE TITLE
Marco temporal y capacidad nominal opex en análisis de costes

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#64]
En la revisión del 27/02 los profesores nos pidieron incluir:

- Marco Temporal: establecer los periodos del proyecto (desarrollo, lanzamiento, etc.).
- Desglosar los costes de OpEx del mantenimiento.
- Explicar la capacidad nominal del OpEx, es decir, cómo variará en función del número de usuarios a los que proporcionemos el servicio.

Para facilitar las revisiones, dejo el enlace al análisis de costes por [aquí](https://uses0-my.sharepoint.com/:w:/r/personal/albperleo_alum_us_es/_layouts/15/Doc.aspx?sourcedoc=%7B7BCE4873-8692-4C88-A0BA-C0F87CE75151%7D&file=11-Cost-Analysis.docx&action=default&mobileredirect=true) 🤙

**Comment by MarioArocaPaez** [comment]
Está súper bien Alberto, llevo un buen rato intentando buscarle alguna pega para hacerme el listo pero no soy capaz. Está todo genial explicado y con todo lo que nos pidieron en el feedback. Muy buen trabajo, ve a tomarte una cerveza o algo :wink:

**Comment by laurolmer** [comment]
Por mi parte también pienso que está espectacular, vaya currazo tío.
