### ISSUE TITLE
Épica/Gestión de alquiler de zonas de garaje

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#7]
Se trata de una épica del proyecto, compuesta por las siguientes subtareas:
* #8 
* #9 
* #10 
* #11 
* #12 
* #13 
* #176

**Comment by 3ralon** [comment]
Debido a una mala planificación no se tuvo en cuenta la funcionalidad de alquilar por parte de un usuario que no es el dueño el garaje. Para ello se ha de utilizar el módulo de booking.
