### ISSUE TITLE
Testear entidades

### ISSUE THREAD

**Issue by CarmenRuizPorcel** [Aparking/AparKing_Backend#76]
Hacer test unitarios de los modelos de nuestra aplicación web.
UML:
https://drive.google.com/file/d/1RUGeWm69W2DxBIdpvVHHlDddUT2H9cu4/view?usp=sharing%5D(https://drive.google.com/file/d/1RUGeWm69W2DxBIdpvVHHlDddUT2H9cu4/view?usp=sharing

Esta issue está compuesta por dos tareas:
#79 
#78

**Comment by CarmenRuizPorcel** [comment]
Se ha reabierto la rama feat/createModel para hacer los tests #77

**Comment by alepervaz** [comment]
Procedo a cerrar la issue tras la subida del código de test necesario a la rama develop
