### ISSUE TITLE
Testear Booking y Authentication

### ISSUE THREAD

**Issue by CarmenRuizPorcel** [Aparking/AparKing_Backend#79]
Crear los test de modelos de las siguientes apps:

- Booking: Comment, Claim y Book
- Authentication: CustomUser y Vehicle

**Comment by alepervaz** [comment]
Subtarea de https://github.com/Aparking/AparKing_Backend/issues/79 terminada

**Comment by alepervaz** [comment]
Subtarea de https://github.com/Aparking/AparKing_Backend/issues/76 terminada
