### ISSUE TITLE
Implementación de Pruebas para Funciones de Parking

### ISSUE THREAD

**Issue by JuanCarlosRL** [Aparking/AparKing_Backend#81]
**Descripción:**

En el marco de las mejoras continuas de nuestra aplicación y siguiendo la implementación realizada en la tarea #15, se reconoce la necesidad de desarrollar y añadir pruebas unitarias específicas para las nuevas funciones de parking.

**Contexto:**

La tarea #15 introdujo varias funciones nuevas al sistema de parking de nuestra aplicación. Para asegurar la integridad y el correcto funcionamiento de estas funciones, es imprescindible desarrollar un conjunto de pruebas unitarias que validen su comportamiento en diferentes escenarios.

**Objetivos:**

- Diseñar y desarrollar pruebas unitarias para cada una de las nuevas funciones introducidas en la tarea #15.
- Asegurar que las pruebas cubran casos de uso comunes así como escenarios de borde.

**Comment by alepervaz** [comment]
Se procede al cierre de la issue tras la comprobación de la funcionalidad y aceptación de la pull request
